### ISSUE TITLE
Set up no compatible using Visual Studio 2019

### ISSUE THREAD

**Issue by DwainSnickles** [Eavilaswayce/YouTube-Downloader#1]
Not a big deal but wanted to say excellent job. I had made one a while ago but went to use it recently and something changed and was struggling to figure out why.
https://github.com/DwainSnickles/YouTubeDownloader-and-Video-Conveter
I will look over your code to see where mine went wrong.
Not sure if why it says setup is not compatible.
Thanks Dwain

**Comment by Noctiamor** [comment]
Oh thank you very much, I'll be honest I didn't think anyone would see this repo haha. The setup project is for Visual Studio 2022 so if you're using Visual Studio 2019 it won't be compatible as you said, you could switch the extension to the 2019 version if you wanted. Your project looks very in depth and I would still consider myself a beginner at C# to be honest. Thanks again!
